facility="daemon"
priority="info"
socket="/var/run/log"
[daily]
program="librenmsDaily"
file="logs/daily.log"
[discovery_wrapper]
program="librenmsDiscoveryWrapper"
file="logs/discovery_wrapper.log"
[librenms]
program="librenms"
file="logs/librenms.log"
[maintenance]
program="librenmsMaintenance"
file="logs/maintenance.log"
[poller_wrapper]
program="librenmsPollerWrapper"
file="logs/poller_wrapper.log"
[service_wrapper]
program="librenmsServiceWrapper"
file="logs/poller_wrapper.log"
